version: "3.8"

services:
  # Auth Service
  auth-service:
    image: vicky0015/zodu-backend-retail-auth-service:uat
    container_name: uat-auth-service-latest
    restart: always
    expose:
      - "4000"
    environment:
      NODE_ENV: production
      PORT: 4000
      DB_HOSTNAME: 72.60.206.59
      DB_PORT: 5432
      DB_USERNAME: zodudb
      DB_PASSWORD: zodu@2025
      DB_NAME: retail_auth_service


  # Restaurant Service
  retail-service:
    image: vicky0015/zodu-backend-retail-service:uat
    container_name: uat-retail-service-latest
    restart: always
    expose:
      - "4001"
    environment:
      NODE_ENV: production
      PORT: 4001
      DB_HOSTNAME: 72.60.206.59
      DB_PORT: 5432
      DB_USERNAME: zodudb
      DB_PASSWORD: zodu@2025
      DB_NAME: retail_restaurant_service
      MINIO_HOST: 72.60.206.59
      MINIO_PORT: 9000
      MINIO_ACCESSKEY: zoduminio
      MINIO_SECRETKEY: zodu@2025
      MINIO_BUCKET_NAME: zodu


  # Employee Service
  employee-service:
    image: vicky0015/zodu-backend-employee-service:uat
    container_name: uat-employee-service-latest
    restart: always
    expose:
      - "4002"
    environment:
      NODE_ENV: production
      PORT: 4002
      DB_HOSTNAME: 72.60.206.59
      DB_PORT: 5432
      DB_USERNAME: zodudb
      DB_PASSWORD: zodu@2025
      DB_NAME: employee-service
      MINIO_HOST: 72.60.206.59
      MINIO_PORT: 9000
      MINIO_ACCESSKEY: zoduminio
      MINIO_SECRETKEY: zodu@2025
      MINIO_BUCKET_NAME: zodu
  
  restaurant-service:
    image: vicky0015/zodu-backend-restaurant-service:uat
    container_name: uat-restaurant-service-latest
    restart: always
    expose:
      - "4003"
    environment:
      NODE_ENV: production
      PORT: 4003
      DB_HOSTNAME: 72.60.206.59
      DB_PORT: 5432
      DB_USERNAME: zodudb
      DB_PASSWORD: zodu@2025
      DB_NAME: restaurant-service
      MINIO_HOST: 72.60.206.59
      MINIO_PORT: 9000
      MINIO_ACCESSKEY: zoduminio
      MINIO_SECRETKEY: zodu@2025
      MINIO_BUCKET_NAME: zodu


  # Payroll Service
  payroll-service:
    image: vicky0015/zodu-backend-payroll-service:uat
    container_name: uat-payroll-service-latest
    restart: always
    expose:
      - "4004"
    environment:
      NODE_ENV: production
      PORT: 4004
      DB_HOSTNAME: 72.60.206.59
      DB_PORT: 5432
      DB_USERNAME: zodudb
      DB_PASSWORD: zodu@2025
      DB_NAME: payroll-service

  checklist-service:
    image: vicky0015/zodu-backend-checklist-service:uat
    container_name: uat-checklist-service-latest
    restart: always
    expose:
      - "4005"
    environment:
      NODE_ENV: production
      PORT: 4005
      DB_HOSTNAME: 72.60.206.59
      DB_PORT: 5432
      DB_USERNAME: zodudb
      DB_PASSWORD: zodu@2025
      DB_NAME: checklist-service
      MINIO_HOST: 72.60.206.59
      MINIO_PORT: 9000
      MINIO_ACCESSKEY: zoduminio
      MINIO_SECRETKEY: zodu@2025
      MINIO_BUCKET_NAME: zodu

  # API Gateway
  apigateway:
    image: vicky0015/zodu-backend-apigateway:uat
    container_name: uat-apigateway-latest
    restart: always
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      AUTH_SERVICE_URL: http://auth-service:4000
      RETAIL_SERVICE_URL: http://retail-service:4001
      EMPLOYEE_SERVICE_URL: http://employee-service:4002
      RESTAURANT_SERVICE_URL: http://restaurant-service:4003
      PAYROLL_SERVICE_URL: http://payroll-service:4004
      CHECKLIST_SERVICE_URL: http://checklist-service:4005
    depends_on:
      - auth-service
      - retail-service
      - employee-service
      - restaurant-service
      - payroll-service
      - checklist-service



