version: "3.9"

services:
  # Auth Service
  auth-service:
    image: vicky0015/zodu-backemd-retail-auth-service:latest
    container_name: retail-auth-service
    restart: always
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOSTNAME: postgres_prod
      DB_PORT: 5432
      DB_USERNAME: zoduprod
      DB_PASSWORD: zodu@2025
      DB_NAME: auth_service


  # Restaurant Service
  retail-service:
    image: vicky0015/zodu-backemd-retail-service:latest
    container_name: retail-service
    restart: always
    expose:
      - "3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOSTNAME: postgres_prod
      DB_PORT: 5432
      DB_USERNAME: zoduprod
      DB_PASSWORD: zodu@2025
      DB_NAME: retail_service
      MINIO_HOST: 72.60.206.59
      MINIO_PORT: 9000
      MINIO_ACCESSKEY: zoduminio
      MINIO_SECRETKEY: zodu@2025
      MINIO_BUCKET_NAME: zodu

  # Employee Service
  employee-service:
    image: vicky0015/zodu-backemd-retail-employee-service:latest
    container_name: retail-employee-service
    restart: always
    expose:
      - "3002"
    environment:
      NODE_ENV: production
      PORT: 3002
      DB_HOSTNAME: postgres_prod
      DB_PORT: 5432
      DB_USERNAME: zoduprod
      DB_PASSWORD: zodu@2025
      DB_NAME: employee-service
      MINIO_HOST: 72.60.206.59
      MINIO_PORT: 9000
      MINIO_ACCESSKEY: zoduminio
      MINIO_SECRETKEY: zodu@2025
      MINIO_BUCKET_NAME: zodu

    restaurant-service:
      image: vicky0015/zodu-backemd-restaurant-service:latest
      container_name: restaurant-service
      restart: always
      expose:
        - "3004"
      environment:
        NODE_ENV: production
        PORT: 3004
        DB_HOSTNAME: postgres_prod
        DB_PORT: 5432
        DB_USERNAME: zoduprod
        DB_PASSWORD: zodu@2025
        DB_NAME: restaurant_service
        MINIO_HOST: 72.60.206.59
        MINIO_PORT: 9000
        MINIO_ACCESSKEY: zoduminio
        MINIO_SECRETKEY: zodu@2025
        MINIO_BUCKET_NAME: zodu

  payroll-service:
    image: vicky0015/zodu-backemd-payroll-service:latest
    container_name: payroll-service
    restart: always
    expose:
      - "3003"
    environment:
      NODE_ENV: production
      PORT: 3003
      DB_HOSTNAME: postgres_prod
      DB_PORT: 5432
      DB_USERNAME: zoduprod
      DB_PASSWORD: zodu@2025
      DB_NAME: payroll-service

  checklist-service:
    image: vicky0015/zodu-backemd-checklist-service:latest
    container_name: checklist-service
    restart: always
    expose:
      - "3005"
    environment:
      NODE_ENV: production
      PORT: 3005
      DB_HOSTNAME: postgres_prod
      DB_PORT: 5432
      DB_USERNAME: zoduprod
      DB_PASSWORD: zodu@2025
      DB_NAME: checklist-service
      MINIO_HOST: 72.60.206.59
      MINIO_PORT: 9000
      MINIO_ACCESSKEY: zoduminio
      MINIO_SECRETKEY: zodu@2025
      MINIO_BUCKET_NAME: zodu

  # API Gateway
    apigateway:
      image: vicky0015/zodu-backemd-retail-apigateway:latest
      container_name: retail-apigateway
      restart: always
      ports:
        - "5000:5000"
      environment:
        PORT: 5000
        AUTH_SERVICE_URL: http://auth-service:3000
        RETAIL_SERVICE_URL: http://retail-service:3001
        EMPLOYEE_SERVICE_URL: http://employee-service:3002
        RESTAURANT_SERVICE_URL: http://restaurant-service:3004
        PAYROLL_SERVICE_URL: http://payroll-service:3003
        CHECKLIST_SERVICE_URL: http://checklist-service:3005
      depends_on:
        - auth-service
        - retail-service
        - employee-service
        - restaurant-service
        - payroll-service
        - checklist-service