const conn = require("../database/connection");

// ── EXPENSE ITEM CATALOG (tbl_expense_menu_items) ────────────────

exports.getCatalogItems = async ({ zodu_id, branch_id, search } = {}) => {
  const conditions = [];
  const values = [];
  let idx = 1;

  if (zodu_id)     { conditions.push(`ei.zodu_id = $${idx++}`);     values.push(zodu_id); }
  if (branch_id)   { conditions.push(`ei.branch_id = $${idx++}`);   values.push(branch_id); }
  if (search) {
    conditions.push(`ei.expense_item_name ILIKE $${idx++}`);
    values.push(`%${search}%`);
  }

  const where = conditions.length ? `WHERE ${conditions.join(" AND ")}` : "";

  const { rows } = await conn.query(
    `SELECT ei.*
     FROM tbl_expense_menu_items ei
     ${where}
     ORDER BY ei.expense_item_name ASC`,
    values
  );
  return rows;
};

exports.createCatalogItem = async (data) => {
  const { rows } = await conn.query(
    `INSERT INTO tbl_expense_menu_items (
       zodu_id, branch_id, expense_item_name, amount, unit
     )
     VALUES ($1,$2,$3,$4,$5)
     RETURNING *`,
    [
      data.zodu_id,
      data.branch_id,
      data.expense_item_name,
      Number(data.amount) || 0,
      Number(data.unit) || 1,
    ]
  );
  return rows[0];
};
// item_id is auto-generated by trg_set_expense_menu_item_id (EXPITEM001, ...)

exports.updateCatalogItem = async (item_uuid, data) => {
  const { rows } = await conn.query(
    `UPDATE tbl_expense_menu_items
     SET expense_item_name = $1,
         amount             = $2,
         unit               = $3,
         is_active          = $4,
         updated_at         = NOW()
     WHERE item_uuid = $5
     RETURNING *`,
    [
      data.expense_item_name,
      Number(data.amount) || 0,
      Number(data.unit) || 1,
      data.is_active !== false,
      item_uuid,
    ]
  );
  return rows[0];
};

exports.deleteCatalogItem = async (item_uuid) => {
  const { rows } = await conn.query(
    `DELETE FROM tbl_expense_menu_items WHERE item_uuid = $1 RETURNING item_uuid`,
    [item_uuid]
  );
  return rows[0];
};

// ── EXPENSE (tbl_expense) ────────────────────────────────────────

exports.createExpense = async (client, data) => {
  const totalAmount = Number(data.total_amount) || 0;
  const paidAmount  = Number(data.paid_amount)  || 0;

  const { rows } = await client.query(
    `INSERT INTO tbl_expense (
       expense_id, zodu_id, branch_id,
       expense_date, category_id, vendor_id,
       total_amount, paid_amount,
       payment_status, notes, attachment_url, due_date
     )
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,
       CASE
         WHEN $8::numeric >= $7::numeric THEN 'paid'
         WHEN $8::numeric = 0            THEN 'pending'
         ELSE 'partial'
       END,
     $9,$10,$11)
     RETURNING *`,
    [
      data.expense_id,
      data.zodu_id,
      data.branch_id,
      data.expense_date,
      data.category_id    || null,
      data.vendor_id      || null,
      totalAmount,
      paidAmount,
      data.notes          || null,
      data.attachment_url ? JSON.stringify(data.attachment_url) : null,
      data.due_date       || null,
    ]
  );
  return rows[0];
};

exports.createExpenseLineItems = async (client, items, expense_id, category_id) => {
  for (const item of items) {
    await client.query(
      `INSERT INTO tbl_expense_items (expense_id, item_id, item_name, qty, price, category_id)
       VALUES ($1,$2,$3,$4,$5,$6)`,
      [
        expense_id,
        item.item_id    || null,
        item.item_name,
        item.qty,
        item.price,
        category_id,
      ]
    );
  }
};

exports.getExpenses = async ({ zodu_id, branch_id, category_id, vendor_id, payment_status, search, page, limit } = {}) => {
  const conditions = [];
  const values = [];
  let idx = 1;

  if (zodu_id)        { conditions.push(`e.zodu_id = $${idx++}`);         values.push(zodu_id); }
  if (branch_id)      { conditions.push(`e.branch_id = $${idx++}`);       values.push(branch_id); }
  if (category_id)    { conditions.push(`e.category_id = $${idx++}`);     values.push(category_id); }
  if (vendor_id)      { conditions.push(`e.vendor_id = $${idx++}`);       values.push(vendor_id); }
  if (payment_status) { conditions.push(`e.payment_status = $${idx++}`);  values.push(payment_status); }
  if (search) {
    conditions.push(`(e.expense_id ILIKE $${idx} OR e.notes ILIKE $${idx})`);
    values.push(`%${search}%`);
    idx++;
  }

  const where = conditions.length ? `WHERE ${conditions.join(" AND ")}` : "";

  const { rows: countRows } = await conn.query(
    `SELECT COUNT(*) FROM tbl_expense e ${where}`,
    values
  );
  const totalRecords = parseInt(countRows[0].count, 10);

  const pageNum   = Math.max(1, parseInt(page, 10)  || 1);
  const limitNum  = Math.max(1, parseInt(limit, 10) || 10);
  const offset    = (pageNum - 1) * limitNum;
  const totalPages = Math.ceil(totalRecords / limitNum);

  const { rows } = await conn.query(
    `SELECT
       e.*,
       c.name AS category_name,
       v.vendor_name,
       v.company_name,
       TO_CHAR(e.expense_date, 'DD Mon YYYY') AS expense_date_formatted,
       TO_CHAR(e.due_date,     'DD Mon YYYY') AS due_date_formatted
     FROM tbl_expense e
     LEFT JOIN tbl_category c ON c.id = e.category_id
     LEFT JOIN tbl_vendor v ON v.vendor_id = e.vendor_id AND v.zodu_id = e.zodu_id AND v.branch_id = e.branch_id
     ${where}
     ORDER BY e.expense_date DESC, e.created_at DESC NULLS LAST
     LIMIT $${idx} OFFSET $${idx + 1}`,
    [...values, limitNum, offset]
  );

  return { data: rows, currentPage: pageNum, totalPages, totalRecords, limit: limitNum };
};

exports.getExpenseById = async (id, { branch_id, zodu_id } = {}) => {
  const conditions = [`e.expense_id = $1`];
  const values = [id];

  if (branch_id) { values.push(branch_id); conditions.push(`e.branch_id = $${values.length}`); }
  if (zodu_id)   { values.push(zodu_id);   conditions.push(`e.zodu_id = $${values.length}`); }

  const { rows: expenseRows } = await conn.query(
    `SELECT
       e.*,
       v.vendor_name,
       v.company_name,
       v.gst,
       v.vendor_phone,
       v.vendor_email,
       v.vendor_address_1,
        v.vendor_address_2,
        v.city As vendor_city,
        v.state As vendor_state,
        v.pincode As vendor_pincode,
        v.vendor_type,
       c.name AS category_name,
       TO_CHAR(e.expense_date, 'DD Mon YYYY') AS expense_date_formatted,
       TO_CHAR(e.due_date,     'DD Mon YYYY') AS due_date_formatted
     FROM tbl_expense e
     LEFT JOIN tbl_category c ON c.id = e.category_id
    LEFT JOIN tbl_vendor v ON v.vendor_id = e.vendor_id AND v.zodu_id = e.zodu_id AND v.branch_id = e.branch_id
     WHERE ${conditions.join(" AND ")}`,
    values
  );

  const expense = expenseRows[0];
  if (!expense) return null;

  const { rows: items } = await conn.query(
    `SELECT
       ei.*,
       c.name AS category_name
     FROM tbl_expense_items ei
     LEFT JOIN tbl_category c ON c.id = ei.category_id
     WHERE ei.expense_id = $1
     ORDER BY ei.expense_item_id ASC`,
    [expense.expense_id]
  );

  const { rows: payments } = await conn.query(
    `SELECT *,
       TO_CHAR(payment_date, 'DD Mon YYYY') AS payment_date_formatted
     FROM tbl_expense_payment
     WHERE expense_id = $1
     ORDER BY payment_date ASC, created_at ASC`,
    [expense.expense_id]
  );

  return { ...expense, items, payments };
};

exports.getExpenseByIdForUpdate = async (client, expense_id) => {
  const { rows } = await client.query(
    `SELECT * FROM tbl_expense WHERE expense_id = $1 FOR UPDATE`,
    [expense_id]
  );
  return rows[0];
};

exports.getExpenseLineItems = async (client, expense_id) => {
  const { rows } = await client.query(
    `SELECT * FROM tbl_expense_items WHERE expense_id = $1`,
    [expense_id]
  );
  return rows;
};

exports.deleteExpenseLineItems = async (client, expense_id) => {
  await client.query(`DELETE FROM tbl_expense_items WHERE expense_id = $1`, [expense_id]);
};

exports.UpdateExpensePayment = async (expense_id, data) => {
  const client = await conn.connect();
  try {
    await client.query("BEGIN");

    const updated = await client.query(
      `UPDATE tbl_expense_payment
       SET paid_amount = $1,
           transaction_type = $2
       WHERE expense_id = $3
       RETURNING *`,
      [data.paid_amount, expense_id]
    );

    await client.query("COMMIT");
    return { success: true, data: updated.rows[0] };
  } catch (err) {
    await client.query("ROLLBACK");
    return { success: false, message: err.message };
  } finally {
    client.release();
  }
};

exports.updateExpense = async (client, expense_id, data) => {
  const totalAmount = Number(data.total_amount) || 0;
  const paidAmount  = Number(data.paid_amount)  || 0;

  await client.query(
    `UPDATE tbl_expense
     SET expense_date   = $1,
         category_id    = $2,
         vendor_id      = $3,
         total_amount   = $4::numeric,
         paid_amount    = $5::numeric,
         due_date      = $9,
         payment_status = CASE
                            WHEN $5::numeric >= $4::numeric THEN 'paid'
                            WHEN $5::numeric = 0            THEN 'pending'
                            ELSE 'partial'
                          END,
         notes          = $6,
         attachment_url = $7,
         updated_at     = NOW()
     WHERE expense_id = $8`,
    [
      data.expense_date,
      data.category_id    || null,
      data.vendor_id      || null,
      totalAmount,
      paidAmount,
      data.notes          || null,
      data.attachment_url ? JSON.stringify(data.attachment_url) : null,
      String(expense_id),
      data.due_date       || null,
    ]
  );
};

exports.deleteExpensePayments = async (client, expense_id) => {
  await client.query(`DELETE FROM tbl_expense_payment WHERE expense_id = $1`, [expense_id]);
};

exports.deleteExpense = async (client, expense_id) => {
  await client.query(`DELETE FROM tbl_expense WHERE expense_id = $1`, [expense_id]);
};

exports.createExpensePayment = async (client, data) => {
  await client.query(
    `INSERT INTO tbl_expense_payment (
       expense_id, zodu_id, branch_id,
       payment_date, paid_amount,
       transaction_type, transaction_id, status
     )
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,
    [
      data.expense_id,
      data.zodu_id,
      data.branch_id,
      data.payment_date,
      data.paid_amount,
      data.transaction_type || "cash",
      data.transaction_id   || null,
      data.status           || "completed",
    ]
  );
};
