const conn = require("../database/connection");


const round = (n) => Math.round(n * 100) / 100;


const ITEM_SELECT = `
  m.*,
  c.name        AS category_name,
  u.name        AS unit_name,
  u.short_name  AS unit_short_name,
  g.gst_rate    AS gst_rate
FROM tbl_menu_items m
LEFT JOIN tbl_category c ON c.id = m.category_id
LEFT JOIN tbl_units    u ON u.id = m.unit
LEFT JOIN tbl_gst      g ON g.id = m.gst_type
`;

/**
 * Get the next sequential number for item_id within a branch.
 * Must be called inside an open transaction (FOR UPDATE prevents races).
 */
exports.getNextItemNumber = async (client, zoduId, branchId) => {
  const result = await client.query(
    `SELECT item_id
     FROM tbl_menu_items
     WHERE zodu_id = $1 AND branch_id = $2
     ORDER BY item_id::bigint DESC
     LIMIT 1
     FOR UPDATE`,
    [zoduId, branchId]
  );

  if (result.rows.length === 0) return 1;

  return parseInt(result.rows[0].item_id, 10) + 1;  // 25901 → 25902
};

/**
 * Insert a new menu item row.
 * item_uuid is auto-generated by Postgres.
 * item_id is passed in (already built by service).
 */
exports.createMenuItem = async (client, data) => {
  const { rows } = await client.query(
    `INSERT INTO tbl_menu_items (
        item_id,        zodu_id,        branch_id,
        item_type,      item_name,
        category_id,    unit,
        mrp,            sell_price,     purchase_price,
        gst_type,       tax_incl_type,
        sku,            barcode,        hsn_code,
        item_img,       status
     ) VALUES (
        $1,$2,$3,
        $4,$5,
        $6,$7,
        $8,$9,$10,
        $11,$12,
        $13,$14,$15,
        $16,$17
     )
     RETURNING *`,
    [
      data.item_id,
      data.zodu_id,
      data.branch_id,
      data.item_type,
      data.item_name,
      data.category_id    ?? null,
      data.unit           ?? null,
      data.mrp            != null ? round(data.mrp)            : null,
      data.sell_price     != null ? round(data.sell_price)     : null,
      data.purchase_price != null ? round(data.purchase_price) : null,
      data.gst_type       ?? null,
      data.tax_incl_type  ?? false,
      data.sku            || null,
      data.barcode        || null,
      data.hsn_code       || null,
      data.item_img       || null,
      data.status         ?? "active",
    ]
  );

  return rows[0];
};

/**
 * Partially update an existing menu item by item_uuid.
 * Only columns present in `data` are updated.
 */
exports.updateMenuItem = async (client, item_uuid, data) => {
  const ALLOWED_FIELDS = [
    "item_name", "item_type", "category_id", "unit",
    "mrp", "sell_price", "purchase_price",
    "gst_type", "tax_incl_type",
    "sku", "barcode", "hsn_code",
    "item_img", "status",
  ];

  const NUMERIC_FIELDS  = ["mrp", "sell_price", "purchase_price"];
  const NULLABLE_FIELDS = ["sku", "barcode", "hsn_code", "item_img"];

  const setClauses = [];
  const values     = [];
  let   idx        = 1;

  for (const field of ALLOWED_FIELDS) {
    if (!(field in data)) continue;

    let val = data[field];

    if (NUMERIC_FIELDS.includes(field) && val != null)  val = round(val);
    if (NULLABLE_FIELDS.includes(field) && val === "")  val = null;

    setClauses.push(`${field} = $${idx++}`);
    values.push(val);
  }

  if (setClauses.length === 0) throw new Error("No valid fields to update");

  values.push(item_uuid);

  const { rows } = await client.query(
    `UPDATE tbl_menu_items
     SET    ${setClauses.join(", ")}
     WHERE  item_uuid = $${idx}
     RETURNING *`,
    values
  );

  if (rows.length === 0) throw new Error("Menu item not found");

  return rows[0];
};

/**
 * Fetch a single item by item_uuid (for response after update).
 */
exports.getMenuItemByUuid = async (client, item_uuid) => {
  const { rows } = await client.query(
    `SELECT 
        m.*,

        -- ✅ Category
        c.id   AS category_id,
        c.name AS category_name,

        -- ✅ Unit
        u.id   AS unit,
        u.short_name AS unit_name,

        g.gst_rate AS gst_rate


     FROM tbl_menu_items m

     LEFT JOIN tbl_category c 
       ON m.category_id = c.id

     LEFT JOIN tbl_units u 
       ON m.unit = u.id

      LEFT JOIN tbl_gst g 
       ON m.gst_type = g.id


     WHERE m.item_uuid = $1`,
    [item_uuid]
  );

  return rows[0] ?? null;
};
/**
 * Paginated list with optional search + filters.
 * Returns { rows, total } — router builds the pagination envelope.
 */
exports.getMenuItems = async (client, { zodu_id, branch_id, search, category_id, item_type, status, page, limit }) => {
  // All WHERE conditions use m. prefix because of the JOIN
  const conditions = ["m.zodu_id = $1", "m.branch_id = $2"];
  const values     = [zodu_id, branch_id];
  let   idx        = 3;
 
  if (search) {
    conditions.push(`(m.item_name ILIKE $${idx} OR m.item_id::text ILIKE $${idx} OR m.barcode ILIKE $${idx})`);
    values.push(`%${search}%`);
    idx++;
  }
 
  if (category_id != null) {
    conditions.push(`m.category_id = $${idx++}`);
    values.push(category_id);
  }
 
  if (item_type) {
    conditions.push(`m.item_type = $${idx++}`);
    values.push(item_type);
  }
 
  if (status) {
    conditions.push(`m.status = $${idx++}`);
    values.push(status);
  }
 
  const where  = `WHERE ${conditions.join(" AND ")}`;
  const offset = (page - 1) * limit;
 
  // Total count — count on base table only (faster, no joins needed)
  const countResult = await client.query(
    `SELECT COUNT(*) FROM tbl_menu_items m ${where}`,
    values
  );
  const total = parseInt(countResult.rows[0].count, 10);
 
  // Paginated rows with joined lookup data
  const { rows } = await client.query(
    `SELECT ${ITEM_SELECT}
     ${where}
     ORDER BY m.item_id::bigint ASC
     LIMIT $${idx} OFFSET $${idx + 1}`,
    [...values, limit, offset]
  );
 
  return { rows, total };
};
 
/**
 * Soft delete — sets status = 'inactive' and deleted_at timestamp.
 * Falls back to hard delete if deleted_at column doesn't exist.
 */
exports.deleteMenuItem = async (client, item_uuid) => {
  // Try soft delete first (status = inactive)
  const { rows } = await client.query(
    `UPDATE tbl_menu_items
     SET status = 'inactive'
     WHERE item_uuid = $1 AND status != 'inactive'
     RETURNING *`,
    [item_uuid]
  );
 
  if (rows.length === 0) {
    // Already inactive or not found — check which
    const check = await client.query(
      `SELECT item_uuid, status FROM tbl_menu_items WHERE item_uuid = $1`,
      [item_uuid]
    );
    if (check.rows.length === 0) throw new Error("Menu item not found");
    // Was already inactive — still return success
    return check.rows[0];
  }
 
  return rows[0];
};
 

const INV_COLS = `
  i.inventory_uuid,
  i.item_uuid,
  i.item_id,
  i.zodu_id,
  i.branch_id,
  m.item_name      AS item_name,
  i.available_qty,
  i.reorder_level,
  i.last_stock_update,
  i.created_at,
  m.sell_price,
  m.purchase_price,
  m.item_img,
  m.item_type,
  m.status        AS item_status,
  m.hsn_code,
  m.barcode,
  c.name          AS category_name,
  u.short_name    AS unit_short_name,
  g.gst_rate
`;
 
const INV_FROM = `
  FROM tbl_inventory i
  LEFT JOIN tbl_menu_items m  ON m.item_uuid  = i.item_uuid
  LEFT JOIN tbl_category   c  ON c.id         = m.category_id
  LEFT JOIN tbl_units      u  ON u.id         = m.unit
  LEFT JOIN tbl_gst        g  ON g.id         = m.gst_type
`;
 
// ─────────────────────────────────────────────────────────────
//  Derived stock status — mirrors the UI badge logic
//    Out of Stock  : available_qty = 0
//    Low Stock     : available_qty > 0 AND available_qty <= reorder_level
//    In Stock      : available_qty > reorder_level
// ─────────────────────────────────────────────────────────────
const STOCK_STATUS_EXPR = `
  CASE
    WHEN i.available_qty = 0                              THEN 'out_of_stock'
    WHEN i.available_qty <= i.reorder_level               THEN 'low_stock'
    ELSE                                                       'in_stock'
  END
`;
 
// ─────────────────────────────────────────────────────────────
//  getInventorySummary
//  Returns the 4 stat cards shown at the top of the screen.
// ─────────────────────────────────────────────────────────────
exports.getInventorySummary = async (client, { zodu_id, branch_id }) => {
  const { rows } = await client.query(
    `SELECT
       -- Total stock value  = SUM(available_qty * purchase_price)
       COALESCE(SUM(i.available_qty * m.purchase_price), 0)   AS total_stock_value,
 
       -- Low stock items
       COUNT(*) FILTER (
         WHERE i.available_qty > 0 AND i.available_qty <= i.reorder_level
       )                                                       AS low_stock_count,
 
       -- Out of stock
       COUNT(*) FILTER (
         WHERE i.available_qty = 0
       )                                                       AS out_of_stock_count,
 
       -- Total active SKUs
       COUNT(*) FILTER (
         WHERE m.status = 'active'
       )                                                       AS total_skus
 
     FROM tbl_inventory i
     LEFT JOIN tbl_menu_items m ON m.item_uuid = i.item_uuid
     WHERE i.zodu_id = $1 AND i.branch_id = $2`,
    [zodu_id, branch_id]
  );
  return rows[0];
};
 
// ─────────────────────────────────────────────────────────────
//  getInventoryList
//  Paginated list with search + stock_status filter.
// ─────────────────────────────────────────────────────────────
exports.getInventoryList = async (
  client,
  { zodu_id, branch_id, search, category_id, stock_status, page, limit }
) => {
  const conditions = ['i.zodu_id = $1', 'i.branch_id = $2'];
  const values     = [zodu_id, branch_id];
  let   idx        = 3;
 
  if (search) {
    conditions.push(
      `(m.item_name ILIKE $${idx} OR i.item_id ILIKE $${idx} OR m.barcode ILIKE $${idx})`
    );
    values.push(`%${search}%`);
    idx++;
  }
 
  if (category_id != null) {
    conditions.push(`m.category_id = $${idx++}`);
    values.push(category_id);
  }
 
  // stock_status filter uses the same CASE expression
  if (stock_status === 'out_of_stock') {
    conditions.push(`i.available_qty = 0`);
  } else if (stock_status === 'low_stock') {
    conditions.push(`i.available_qty > 0 AND i.available_qty <= i.reorder_level`);
  } else if (stock_status === 'in_stock') {
    conditions.push(`i.available_qty > i.reorder_level`);
  }
 
  const where  = `WHERE ${conditions.join(' AND ')}`;
  const offset = (page - 1) * limit;
 
  // Count (no joins needed for count — use base table)
  const countResult = await client.query(
    `SELECT COUNT(*)
     FROM tbl_inventory i
     LEFT JOIN tbl_menu_items m ON m.item_uuid = i.item_uuid
     ${where}`,
    values
  );
  const total = parseInt(countResult.rows[0].count, 10);
 
  // Rows with full join
  const { rows } = await client.query(
    `SELECT
       ${INV_COLS},
       ${STOCK_STATUS_EXPR} AS stock_status,
       -- stock value for this row
       ROUND(i.available_qty * COALESCE(m.purchase_price, 0), 2) AS stock_value
     ${INV_FROM}
     ${where}
     ORDER BY i.item_id::bigint ASC
     LIMIT $${idx} OFFSET $${idx + 1}`,
    [...values, limit, offset]
  );
 
  return { rows, total };
};
 
// ─────────────────────────────────────────────────────────────
//  getInventoryByUuid
// ─────────────────────────────────────────────────────────────
exports.getInventoryByUuid = async (client, inventory_uuid) => {
  const { rows } = await client.query(
    `SELECT
       ${INV_COLS},
       ${STOCK_STATUS_EXPR} AS stock_status,
       ROUND(i.available_qty * COALESCE(m.purchase_price, 0), 2) AS stock_value
     ${INV_FROM}
     WHERE i.inventory_uuid = $1`,
    [inventory_uuid]
  );
  return rows[0] ?? null;
};
 
// ─────────────────────────────────────────────────────────────
//  getInventoryByItemUuid  (used when opening Adjust Stock modal)
// ─────────────────────────────────────────────────────────────
exports.getInventoryByItemUuid = async (client, item_uuid) => {
  const { rows } = await client.query(
    `SELECT
       ${INV_COLS},
       ${STOCK_STATUS_EXPR} AS stock_status,
       ROUND(i.available_qty * COALESCE(m.purchase_price, 0), 2) AS stock_value
     ${INV_FROM}
     WHERE i.item_uuid = $1`,
    [item_uuid]
  );
  return rows[0] ?? null;
};
 
// ─────────────────────────────────────────────────────────────
//  adjustStock
//  Applies ADD or SUBTRACT to available_qty atomically.
//  Returns the updated inventory row.
// ─────────────────────────────────────────────────────────────
exports.adjustStock = async (
  client,
  { inventory_uuid, adjustment_type, adjustment_qty }
) => {
  const qty = round(Math.abs(adjustment_qty));
 
  const operator = adjustment_type === 'subtract' ? '-' : '+';
 
  const { rows } = await client.query(
    `UPDATE tbl_inventory
     SET
       available_qty      = available_qty ${operator} $1,
       last_stock_update  = NOW()
     WHERE inventory_uuid = $2
     RETURNING *`,
    [qty, inventory_uuid]
  );
 
  if (rows.length === 0) throw new Error('Inventory record not found');
  return rows[0];
};
 
// ─────────────────────────────────────────────────────────────
//  createInventoryRecord  (called when a new menu item is created)
// ─────────────────────────────────────────────────────────────
exports.createInventoryRecord = async (client, data) => {
  const { rows } = await client.query(
    `INSERT INTO tbl_inventory (
       item_uuid, item_id, zodu_id, branch_id,
       item_name, available_qty, reorder_level
     ) VALUES ($1,$2,$3,$4,$5,$6,$7)
     ON CONFLICT (item_uuid) DO NOTHING
     RETURNING *`,
    [
      data.item_uuid,
      data.item_id,
      data.zodu_id,
      data.branch_id,
      data.item_name,
      data.available_qty  ?? 0,
      data.reorder_level  ?? 0,
    ]
  );
  return rows[0] ?? null;
};

exports.createStockLedger = async (client, data) => {
  const { rows } = await client.query(
    `INSERT INTO tbl_stock_ledger (
      item_uuid, item_id, zodu_id, branch_id,
      item_name, transaction_type,
      reference_id, qty_change,
      stock_before, stock_after, notes
    )
    VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
    RETURNING *`,
    [
      data.item_uuid,
      data.item_id,
      data.zodu_id,
      data.branch_id,
      data.item_name,
      data.transaction_type,
      data.reference_id,
      data.qty_change,
      data.stock_before,
      data.stock_after,
      data.notes,
    ]
  );
  return rows[0];
};



exports.getStockHistoryRepo = async ({ item_uuid, zodu_id, branch_id }) => {
  const query = `
    SELECT 
      l.ledger_id,
      l.item_uuid,
      l.item_id,

      -- Prefer menu name, fallback to ledger name
      COALESCE(m.item_name, l.item_name) AS item_name,

      l.transaction_type,
      l.qty_change,
      l.stock_before,
      l.stock_after,
      l.notes,
 TO_CHAR(l.created_at, 'DD Mon YYYY, HH12:MI AM') AS created_at,
      inv.available_qty,
      inv.reorder_level,

      CASE 
        WHEN l.qty_change > 0 THEN 'IN'
        WHEN l.qty_change < 0 THEN 'OUT'
        ELSE 'ADJUST'
      END as movement_type

    FROM tbl_stock_ledger l

    -- ✅ Inventory (current stock)
    LEFT JOIN tbl_inventory inv
      ON inv.item_uuid = l.item_uuid
      AND inv.zodu_id = l.zodu_id
      AND inv.branch_id = l.branch_id

    -- ✅ Menu Items (latest name)
    LEFT JOIN tbl_menu_items m
      ON m.item_uuid = l.item_uuid

    WHERE l.item_uuid = $1
      AND l.zodu_id = $2
      AND l.branch_id = $3

    ORDER BY l.created_at DESC
  `;

  const values = [item_uuid, zodu_id, branch_id];

  const result = await conn.query(query, values);
  return result.rows;
};
